In [1]:
#Importing the libraties:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
%matplotlib inline

In [2]:
#Reading the dataset:
d = pd.read_csv("50_Startups.csv")
d

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [7]:
X = d.iloc[:, :-1].values
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [5]:
y = d.iloc[:, 4].values
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('encoder',OneHotEncoder(), [3])], remainder='passthrough')
d = np.array(ct.fit_transform(d),dtype= np.str)
d

array([['0.0', '0.0', '1.0', '165349.2', '136897.8', '471784.1',
        '192261.83'],
       ['1.0', '0.0', '0.0', '162597.7', '151377.59', '443898.53',
        '191792.06'],
       ['0.0', '1.0', '0.0', '153441.51', '101145.55', '407934.54',
        '191050.39'],
       ['0.0', '0.0', '1.0', '144372.41', '118671.85', '383199.62',
        '182901.99'],
       ['0.0', '1.0', '0.0', '142107.34', '91391.77', '366168.42',
        '166187.94'],
       ['0.0', '0.0', '1.0', '131876.9', '99814.71', '362861.36',
        '156991.12'],
       ['1.0', '0.0', '0.0', '134615.46', '147198.87', '127716.82',
        '156122.51'],
       ['0.0', '1.0', '0.0', '130298.13', '145530.06', '323876.68',
        '155752.6'],
       ['0.0', '0.0', '1.0', '120542.52', '148718.95', '311613.29',
        '152211.77'],
       ['1.0', '0.0', '0.0', '123334.88', '108679.17', '304981.62',
        '149759.96'],
       ['0.0', '1.0', '0.0', '101913.08', '110594.11', '229160.95',
        '146121.95'],
       ['1.0', '0.

In [9]:
#We have converted the state column into 3 dummy columns(dummy variables):
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('encoder',OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X),dtype= np.str)
X

array([['0.0', '0.0', '1.0', '165349.2', '136897.8', '471784.1'],
       ['1.0', '0.0', '0.0', '162597.7', '151377.59', '443898.53'],
       ['0.0', '1.0', '0.0', '153441.51', '101145.55', '407934.54'],
       ['0.0', '0.0', '1.0', '144372.41', '118671.85', '383199.62'],
       ['0.0', '1.0', '0.0', '142107.34', '91391.77', '366168.42'],
       ['0.0', '0.0', '1.0', '131876.9', '99814.71', '362861.36'],
       ['1.0', '0.0', '0.0', '134615.46', '147198.87', '127716.82'],
       ['0.0', '1.0', '0.0', '130298.13', '145530.06', '323876.68'],
       ['0.0', '0.0', '1.0', '120542.52', '148718.95', '311613.29'],
       ['1.0', '0.0', '0.0', '123334.88', '108679.17', '304981.62'],
       ['0.0', '1.0', '0.0', '101913.08', '110594.11', '229160.95'],
       ['1.0', '0.0', '0.0', '100671.96', '91790.61', '249744.55'],
       ['0.0', '1.0', '0.0', '93863.75', '127320.38', '249839.44'],
       ['1.0', '0.0', '0.0', '91992.39', '135495.07', '252664.93'],
       ['0.0', '1.0', '0.0', '119943.24', '1

In [10]:
#Splitting the data into training set and test set:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test =  train_test_split(X, y, test_size =0.2, random_state = 0)

In [14]:
X_train = X_train.astype(np.float64)
X_test = X_test.astype(np.float64)

In [15]:
#fitting the model in the linear regression model on the training set 
from sklearn.linear_model import LinearRegression
lr =  LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
#Predicting on X training data:
y_prediction = lr.predict(X_test)
y_prediction

array([103015.20159796, 132582.27760816, 132447.73845174,  71976.09851258,
       178537.48221055, 116161.24230166,  67851.69209676,  98791.73374686,
       113969.43533013, 167921.06569551])

In [17]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [18]:
#Till now, we have predicted based on all the columns and the next task is to find out.

In [19]:
X = np.append(arr = np.ones((50,1)).astype(int), values = X, axis = 1)
X

array([['1', '0.0', '0.0', '1.0', '165349.2', '136897.8', '471784.1'],
       ['1', '1.0', '0.0', '0.0', '162597.7', '151377.59', '443898.53'],
       ['1', '0.0', '1.0', '0.0', '153441.51', '101145.55', '407934.54'],
       ['1', '0.0', '0.0', '1.0', '144372.41', '118671.85', '383199.62'],
       ['1', '0.0', '1.0', '0.0', '142107.34', '91391.77', '366168.42'],
       ['1', '0.0', '0.0', '1.0', '131876.9', '99814.71', '362861.36'],
       ['1', '1.0', '0.0', '0.0', '134615.46', '147198.87', '127716.82'],
       ['1', '0.0', '1.0', '0.0', '130298.13', '145530.06', '323876.68'],
       ['1', '0.0', '0.0', '1.0', '120542.52', '148718.95', '311613.29'],
       ['1', '1.0', '0.0', '0.0', '123334.88', '108679.17', '304981.62'],
       ['1', '0.0', '1.0', '0.0', '101913.08', '110594.11', '229160.95'],
       ['1', '1.0', '0.0', '0.0', '100671.96', '91790.61', '249744.55'],
       ['1', '0.0', '1.0', '0.0', '93863.75', '127320.38', '249839.44'],
       ['1', '1.0', '0.0', '0.0', '91992.39', '

In [20]:
X = X.astype(np.float64)
y = y.astype(np.float64)
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.6534920e+05, 1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.6259770e+05, 1.5137759e+05, 4.4389853e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.5344151e+05, 1.0114555e+05, 4.0793454e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.4437241e+05, 1.1867185e+05, 3.8319962e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.4210734e+05, 9.1391770e+04, 3.6616842e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.3187690e+05, 9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.3461546e+05, 1.4719887e+05, 1.2771682e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.3029813e+05, 1.4553006e+05, 3.2387668e+05],
       [1.0000000e+00, 0

In [21]:
X_optimal = X[:,[0,1,2,3,4,5,6]]

In [22]:
regressor_ols = sm.OLS(y, X_optimal).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Fri, 22 Jan 2021   Prob (F-statistic):           1.34e-27
Time:                        08:22:06   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.763e+04   5073.636      7.417      0.000    2.74e+04    4.79e+04
x1          1.249e+04   2449.797      5.099      0.000    7554.868    1.74e+04
x2          1.269e+04   2726.700      4.654      0.000    7195.596    1.82e+04
x3          1.245e+04   2486.364      5.007      0.000    7439.285    1.75e+04
x4             0.8060      0.046     17.369      0.000       0.712       0.900
x5            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x6             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     2.69e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [23]:
#From the conclusion, We have to eliminate the administration column since the probability value is high compared 
#to other columns by backward elimination steps.
#We have to eliminate the companies which invest more on administration.

In [24]:
X_optimal = X[:,[0,1,2,3,4,6]]
regressor_ols = sm.OLS(y, X_optimal).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     215.8
Date:                Fri, 22 Jan 2021   Prob (F-statistic):           9.72e-29
Time:                        08:22:09   Log-Likelihood:                -525.53
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1071.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.525e+04   2100.376     16.782      0.000     3.1e+04    3.95e+04
x1          1.171e+04   1910.312      6.130      0.000    7861.854    1.56e+04
x2          1.185e+04   2170.903      5.459      0.000    7477.785    1.62e+04
x3          1.169e+04   1988.428      5.879      0.000    7684.996    1.57e+04
x4             0.7967      0.042     18.771      0.000       0.711       0.882
x5             0.0298      0.016      1.842      0.072      -0.003       0.062
==============================================================================
Omnibus:                       14.640   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.037
Skew:                          -0.938   Prob(JB):                     2.70e-05
Kurtosis:                       5.565   Cond. No.                     6.69e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 7.33e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [106]:
X_optimal = X[:,[0,1,2,3,6]]
regressor_ols = sm.OLS(y, X_optimal).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     416.4
Date:                Tue, 19 Jan 2021   Prob (F-statistic):           1.26e-30
Time:                        13:38:07   Log-Likelihood:                -527.42
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      47   BIC:                             1067.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.643e+04    956.843     17.170      0.000    1.45e+04    1.84e+04
x1          1.643e+04    956.843     17.170      0.000    1.45e+04    1.84e+04
x2          1.643e+04    956.843     17.170      0.000    1.45e+04    1.84e+04
x3          -563.3912   2869.305     -0.196      0.845   -6335.689    5208.906
x4             0.8535      0.030     28.532      0.000       0.793       0.914
==============================================================================
Omnibus:                       13.278   Durbin-Watson:                   1.108
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               17.212
Skew:                          -0.905   Prob(JB):                     0.000183
Kurtosis:                       5.233   Cond. No.                     4.94e+21
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.54e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""